### ISSUE TITLE
Feature suggestion: make -q also suppress generation information

### ISSUE THREAD

**Issue by purvaldur** [aflaag/pokemon-icat#13]
Currently I'm able to pass the -q parameter to suppress the pokemon name above the sprite, but it still prints the generation below it.
![image](https://github.com/user-attachments/assets/c5a07160-5ca0-42e1-9cf6-e6423859f3e7)

I would love for the -q parameter to also suppress the generation so it's JUST the pokemon sprite and nothing else.

**Comment by DavideGalilei** [comment]
Fixed in https://github.com/aflaag/pokemon-icat/pull/15, waiting for it to be merged.
