### ISSUE TITLE
[improvement] async requests

### ISSUE THREAD

**Issue by imsamuka** [aflaag/pokemon-icat#2]
The `setup_icons.py` can be considerably faster using asynchronous requests.

The current script takes ~7 minutes (~420 seconds) to run. If you make 10 requests for batch, 1s delay between each batch, it would take ~90 seconds to download everything. The server probably can deal with smaller delays though.

**Comment by aflaag** [comment]
that's a pretty interesting approach, except for the fact that i've never written anything async in python so i don't really know how to do it ahahahahah, PR are accepted of course
