### ISSUE TITLE
Specific Pokemon

### ISSUE THREAD

**Issue by ghost** [aflaag/pokemon-icat#4]
Hey. I was just wanting to know if there was a way that we could specify a particular pokemon. Thank you <3

**Comment by aflaag** [comment]
it's not implemented, but i mean yeah that could be an option too, shouldn't be that hard to implement either

**Comment by aflaag** [comment]
https://github.com/ph04/pokemon-icat/blob/main/README.md?plain=1#L46 updated, this should work, let me now if i broke something 👍🏼
