### ISSUE TITLE
Incorrect functionality when using with fish on Iterm2 on Mac

### ISSUE THREAD

**Issue by nakranirudh** [aflaag/pokemon-icat#6]
I tried to configure everything according to my own setup and ended up trying to make it work on Iterm with fish and using imgcat. However I am running into the following error as shown in the screenshot. Any help regarding why this is happening?

![Screenshot 2022-08-08 at 8 53 01 PM](https://user-images.githubusercontent.com/84345588/183539387-32526f10-f3d9-4bbd-a606-58c6210974b5.png)

**Comment by aflaag** [comment]
Does your setup work on other images?

**Comment by nakranirudh** [comment]
Shortly after posting this, I stopped trying to debug it. I will check the functionality of the tool and get back to you. Setting this up was the first time I was trying to use imgcat

**Comment by aflaag** [comment]
Ok let me know!
