### ISSUE TITLE
Wrong command in .pokemon-icat.sh

### ISSUE THREAD

**Issue by Sommerrolle** [aflaag/pokemon-icat#9]
This command in line 14 of file `pokemon-icat.sh` did not work for me: 
`kitten icat --align left --silent $HOME/.pokemon-icat/pokemon-icons/$pokemon.png
`

I changed it to 
`kitty +kitten icat --align left --silent $HOME/.pokemon-icat/pokemon-icons/$pokemon.png`

I don't know is this is a change from the kitty terminal itself. Just wanted to mention it if someone else had a similar problem :)

**Comment by kovidgoyal** [comment]
kitten icat is correct for modern kitty, kitty +kitten icat is needed only for older kitty releases, but will work on newer ones as well.

**Comment by aflaag** [comment]
> kitten icat is correct for modern kitty, kitty +kitten icat is needed only for older kitty releases, but will work on newer ones as well.

so, do you suggest me to change that line to make sure it works on older versions as well?

**Comment by kovidgoyal** [comment]
On Wed, Sep 06, 2023 at 08:26:53AM -0700, Alessio Bandiera wrote:
> > kitten icat is correct for modern kitty, kitty +kitten icat is needed only for older kitty releases, but will work on newer ones as well.
> 
> so, do you suggest me to change that line to make sure it works on older versions as well?

It's a bit slower as kitty +kitten icat will end up calling kitten icat
but not significantly, so its up to you if the tradeoff is worth it.

**Comment by aflaag** [comment]
> On Wed, Sep 06, 2023 at 08:26:53AM -0700, Alessio Bandiera wrote: > kitten icat is correct for modern kitty, kitty +kitten icat is needed only for older kitty releases, but will work on newer ones as well. so, do you suggest me to change that line to make sure it works on older versions as well?
> It's a bit slower as kitty +kitten icat will end up calling kitten icat but not significantly, so its up to you if the tradeoff is worth it.

ok, thank you!
